sudo: required
dist: xenial
apt:
  packages:
    - openjdk8

language: scala
jdk: openjdk8

before_install:
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

matrix:
  include:
    - script: sbt +test
    - env:
        - CHANGE_MINIKUBE_NONE_USER=true # This moves Kubernetes specific config files.
      install:
        - script/install-minikube.sh
      script: sbt publishLocal integrationTest/scripted

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com/lightbend/rp/sbtreactiveapp
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
